# Generated by Django 4.2.4 on 2023-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tfa_secret",
            field=models.CharField(default="", max_length=255),
        ),
    ]
